=== AndreLMoreira01/COBOL/COBOL/AcuGT/sample/xml/bookfile.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="unqualified">
  <xs:annotation>
    <xs:documentation>
      Created by AcuXML(tm) version 6.0.0 Alpha (2002-10-30) on 2002/10/30
    </xs:documentation>
  </xs:annotation>

  <xs:element name="bookfile">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="transaction"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="transaction">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Lender"/>
        <xs:element ref="Borrower"/>
        <xs:element minOccurs="0" ref="note"/>
        <xs:element ref="books"/>
      </xs:sequence>
    <xs:attribute name="borrowDate" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="Lender">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="street"/>
        <xs:element ref="city"/>
        <xs:element ref="state"/>
      </xs:sequence>
    <xs:attribute name="phone" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="Borrower">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="street"/>
        <xs:element ref="city"/>
        <xs:element ref="state"/>
      </xs:sequence>
    <xs:attribute name="phone" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="books">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="book" maxOccurs="10"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="book">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="bookTitle"/>
        <xs:element ref="pubDate"/>
        <xs:element ref="replacementValue"/>
        <xs:element ref="maxDaysOut"/>
      </xs:sequence>
    <xs:attribute name="bookID" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="name" type="simplename" />
  <xs:simpleType name="simplename">
      <xs:restriction base="xs:string">
        <xs:maxLength value="30"/>
      </xs:restriction>
  </xs:simpleType>

  <xs:element name="street" type="simplestreet" />
  <xs:simpleType name="simplestreet">
      <xs:restriction base="xs:string">
        <xs:maxLength value="30"/>
      </xs:restriction>
  </xs:simpleType>

  <xs:element name="city" type="simplecity" />
  <xs:simpleType name="simplecity">
    <xs:restriction base="xs:string">
        <xs:maxLength value="30"/>
      </xs:restriction>
  </xs:simpleType>

  <xs:element name="state" type="simplestate" />
  <xs:simpleType name="simplestate">
      <xs:restriction base="xs:string">
        <xs:maxLength value="2"/>
      </xs:restriction>
    </xs:simpleType>

  <xs:element name="note" type="simplenote" />
    <xs:simpleType name="simplenote">
      <xs:restriction base="xs:string">
        <xs:maxLength value="255"/>
      </xs:restriction>
    </xs:simpleType>

  <xs:element name="bookTitle" type="simplebookTitle" />
  <xs:simpleType name="simplebookTitle">
      <xs:restriction base="xs:string">
        <xs:maxLength value="30"/>
      </xs:restriction>
    </xs:simpleType>

  <xs:element name="pubDate" type="simplepubDate" />
  <xs:simpleType name="simplepubDate">
     <xs:restriction base="xs:string">
        <xs:maxLength value="30"/>
      </xs:restriction>
    </xs:simpleType>

  <xs:element name="replacementValue" type="simplereplacementValue" />
  <xs:simpleType name="simplereplacementValue">
      <xs:restriction base="xs:string">
        <xs:maxLength value="7"/>
      </xs:restriction>
  </xs:simpleType>

  <xs:element name="maxDaysOut" type="simplemaxDaysOut" />
  <xs:simpleType name="simplemaxDaysOut">
      <xs:restriction base="xs:string">
        <xs:maxLength value="3"/>
      </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== AndreLMoreira01/COBOL/COBOL/AcuGT/sample/xml/bookfile.xml
<?xml version="1.0"?>
<bookfile
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceschemaLocation="bookfile.xsd">
  <transaction borrowDate="2001-10-15">
    <Lender phone="607.555.2222">
      <name>Doug Glass</name>
      <street>416 Disk Drive</street>
      <city>Medfield</city>
      <state>MA</state>
    </Lender>
    <Borrower phone="310.555.1111">
      <name>Britta Regensburg</name>
      <street>219 Union Drive</street>
      <city>Medfield</city>
      <state>CA</state>
    </Borrower>
    <note>Lender wants these back in two weeks!</note>
    <books>
      <book bookID="123-4567-890">
        <bookTitle>Earthquakes for Breakfast</bookTitle>
        <pubDate>2001-10-20</pubDate>
        <replacementValue>15.95</replacementValue>
        <maxDaysOut>14</maxDaysOut>
      </book>
      <book bookID="123-4567-891">
        <bookTitle>Avalanches for Lunch</bookTitle>
        <pubDate>2001-10-21</pubDate>
        <replacementValue>19.99</replacementValue>
        <maxDaysOut>14</maxDaysOut>
      </book>
      <book bookID="123-4567-892">
        <bookTitle>Meteor Showers for Dinner</bookTitle>
        <pubDate>2001-10-22</pubDate>
        <replacementValue>11.95</replacementValue>
        <maxDaysOut>14</maxDaysOut>
      </book>
      <book bookID="123-4567-893">
        <bookTitle>Snacking on Volcanoes</bookTitle>
        <pubDate>2001-10-23</pubDate>
        <replacementValue>17.99</replacementValue>
        <maxDaysOut>14</maxDaysOut>
      </book>
    </books>
  </transaction>
  <transaction borrowDate="2002-11-18">
    <Lender phone="619.555.2222">
      <name>Philip Glass</name>
      <street>146 Floppy Drive</street>
      <city>Chicago</city>
      <state>IL</state>
    </Lender>
    <Borrower phone="310.555.1111">
      <name>Britta Regensburg</name>
      <street>219 Union Drive</street>
      <city>Medfield</city>
      <state>CA</state>
    </Borrower>
    <books>
      <book bookID="321-4567-890">
        <bookTitle>Day Tripping in San Francisco</bookTitle>
        <pubDate>1998-11-20</pubDate>
        <replacementValue>25.95</replacementValue>
        <maxDaysOut>28</maxDaysOut>
      </book>
      <book bookID="321-4567-891">
        <bookTitle>3 Ways to better skiing</bookTitle>
        <pubDate>19889-9-2</pubDate>
        <replacementValue>9.99</replacementValue>
        <maxDaysOut>3</maxDaysOut>
      </book>
      <book bookID="321-4567-892">
        <bookTitle>Skylines of Utah</bookTitle>
        <pubDate>1998-4-1</pubDate>
        <replacementValue>31.95</replacementValue>
        <maxDaysOut>14</maxDaysOut>
      </book>
    </books>
  </transaction>
</bookfile>
